services:
  - type: web
    name: expense-manager-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # You'll set this manually in Render dashboard
      - key: FRONTEND_URL
        sync: false  # You'll set this after frontend deployment